defaults:
  - _self_
  - trainer: default
  - model: mlp-classifier
  - dataset: mnist
  - logger: tensorboard
  - hydra: default

seed: 42

# Output directory
root_dir: ${model.name}/${dataset.name}
run_name: ${now:%y-%m-%dT%H:%M:%S}_${seed}